GitHub-CI: add build with latest Mono version

diff --git a/.github/workflows/auto-ci-builds.yml b/.github/workflows/auto-ci-builds.yml
--- a/.github/workflows/auto-ci-builds.yml
+++ b/.github/workflows/auto-ci-builds.yml
@@ -123,3 +123,41 @@ jobs:
     - name: build
       run: |
         make
+
+  build_Mono-latest: # latest Mono version
+    runs-on: ubuntu-latest
+    container: mono:latest
+    steps:
+    - uses: actions/checkout@v1
+    # the official Mono container doesn't have sudo and https support for
+    # APT pre-installed
+    - name: install apt-transport-https and sudo
+      run: |
+        apt update > /dev/null || true # ignore exit code so mixed HTTP and
+          # HTTPS source lines won't fail before https support is intalled below
+        apt install --yes apt-transport-https > /dev/null
+        apt update > /dev/null
+        apt install --yes sudo > /dev/null
+    # workaround for https://github.com/actions/runner/issues/2033
+    - name: workaround failing git ownership check
+      run: |
+        sudo apt install --yes git > /dev/null
+        git config --global --add safe.directory '*'
+    - name: install build dependencies from debian/control
+      run: |
+        sudo apt install --yes devscripts equivs > /dev/null
+        #sudo mk-build-deps --install debian/control
+        # "mk-build-deps --install" fails to install all packages, while apt can
+        # install all packages without issues, so we skip "--install" here
+        sudo mk-build-deps debian/control
+        dpkg --info ./smuxi-build-deps_*.deb
+        sudo apt install --yes ./smuxi-build-deps_*.deb
+    - name: check mono version
+      run: |
+        mono --version
+    - name: autogen and configure
+      run: |
+        ./autogen.sh
+    - name: build
+      run: |
+        make
